/**
 * `gen:e2e-tests` — spec `e2eTests` (natural language, per page) → Playwright
 * test scaffolds. Deterministic
 * emission; the agent loop fills each body through the {@link AiClient}, so the
 * suite becomes the app's own eval (§3-L4B). Under `MOCK_AI` the bodies are
 * canned and the whole thing runs in CI without a key.
 */

import type { PageSpec } from '@maxstack/spec'
import type { AiClient } from './ai.ts'
import { resourceOf } from './pipeline.ts'

export interface E2eTestCase {
	/** Stable id — `<pageId>:<index>` — the mock keys canned bodies on it. */
	key: string
	/** The natural-language test from the spec. */
	text: string
	/** The Playwright body once filled (undefined in a scaffold). */
	body?: string
}

export interface E2eSuite {
	/** Repo-relative spec file, e.g. `e2e/task.spec.ts`. */
	file: string
	resource: string
	/** Page heading, used for the `test.describe` title. */
	title: string
	/** The page route, used as the suite's base URL. */
	route: string
	cases: E2eTestCase[]
}

/** Plan the suite for a page — one case per `e2eTests` string. */
export function planE2eTests(page: PageSpec): E2eSuite {
	const resource = resourceOf(page)
	return {
		file: `e2e/${resource}.spec.ts`,
		resource,
		title: page.name,
		route: page.route,
		cases: (page.e2eTests ?? []).map((text, i) => ({
			key: `${page.id}:${i}`,
			text,
		})),
	}
}

const PLACEHOLDER = '// TODO(agent): fill from the e2eTests spec'

function indent(body: string): string {
	return body
		.split('\n')
		.map((line) => (line ? `\t\t${line}` : line))
		.join('\n')
}

function renderCase(c: E2eTestCase): string {
	const body = c.body ?? PLACEHOLDER
	return [
		`\ttest(${JSON.stringify(c.text)}, async ({ page }) => {`,
		indent(body),
		'\t})',
	].join('\n')
}

/** Render the suite to a Playwright spec file (scaffold if bodies are unfilled). */
export function renderE2eSuite(suite: E2eSuite): string {
	return [
		'// Generated by maxstack gen:e2e-tests. Bodies are filled by the agent',
		'// loop; re-run with MOCK_AI=1 for deterministic, keyless CI stubs.',
		"import { expect, test } from '@playwright/test'",
		'',
		`const baseURL = ${JSON.stringify(suite.route)}`,
		'',
		`test.describe(${JSON.stringify(suite.title)}, () => {`,
		suite.cases.map(renderCase).join('\n\n'),
		'})',
		'',
	].join('\n')
}

/** The scaffold: bodies are TODO placeholders. */
export function genE2eTests(page: PageSpec): {
	suite: E2eSuite
	content: string
} {
	const suite = planE2eTests(page)
	return { suite, content: renderE2eSuite(suite) }
}

/**
 * The agent loop: fill every test body through the AI port. Returns the suite
 * with bodies populated plus the rendered spec file. `expect` is referenced by
 * the mock bodies so it stays imported.
 */
export async function fillE2eTests(
	page: PageSpec,
	ai: AiClient,
): Promise<{ suite: E2eSuite; content: string; filled: number }> {
	const suite = planE2eTests(page)
	let filled = 0
	for (const c of suite.cases) {
		c.body = await ai.complete({
			generator: 'e2e-tests',
			key: c.key,
			prompt: c.text,
		})
		filled++
	}
	return { suite, content: renderE2eSuite(suite), filled }
}
