/**
 * **One seam, one derivation**.
 *
 * The four non-page seams — schedules, sources, imports and
 * live channels — are now emitted by `maxstack gen` (`generateProject`),
 * reported on by `maxstack drift` (`regenTargets`) and generated by the harness
 * during an eval. Three surfaces, and until #235 only the harness ran any of
 * them, which is exactly how the projections behind them drifted apart without
 * anybody noticing: `@maxstack/spec-derive`'s `specTo*Descriptors` and
 * `@maxstack/mcp`'s `*Descriptors` are two copies of the same fact.
 *
 * They are two copies because the boundary policy says so —
 * `scripts/boundaries.config.json` does not let L4 import `@maxstack/mcp` — so
 * the honest option is not to delete one but to **pin that they agree**, the way
 * the spec↔features SSRF check is pinned. This app is the one place that may
 * import both.
 *
 * Run over the corpus rather than a hand-built spec: the disagreement that
 * matters is the one a real declaration produces, and the corpus apps are what
 * the expressibility ratio is measured on. A divergence here means the tree a
 * user generates and the tree the eval scores are different trees, which would
 * make every number in FINDINGS a measurement of something nobody runs.
 */

import { examples } from '@maxstack/examples'
import {
	specToImporterDescriptors,
	specToLiveDescriptors,
	specToScheduleDescriptors,
	specToSourceDescriptors,
} from '@maxstack/spec-derive'
import {
	importerDescriptors,
	liveDescriptors,
	scheduleDescriptors,
	sourceDescriptors,
} from '@maxstack/mcp'
import { describe, expect, it } from 'vitest'

const FAMILIES = [
	{
		name: 'schedules',
		cli: scheduleDescriptors,
		harness: specToScheduleDescriptors,
	},
	{ name: 'sources', cli: sourceDescriptors, harness: specToSourceDescriptors },
	{
		name: 'imports',
		cli: importerDescriptors,
		harness: specToImporterDescriptors,
	},
	{ name: 'live', cli: liveDescriptors, harness: specToLiveDescriptors },
] as const

describe('the CLI and the harness derive the same seam', () => {
	for (const family of FAMILIES) {
		it(`agrees on the ${family.name} descriptors for every corpus app`, () => {
			for (const benchmark of examples) {
				expect(
					family.cli(benchmark.spec),
					`${family.name} descriptors disagree for ${benchmark.id}`,
				).toEqual(family.harness(benchmark.spec))
			}
		})
	}

	it('is not vacuous — the corpus declares every family', () => {
		// A green suite over eleven apps that declare nothing would pin nothing.
		for (const family of FAMILIES) {
			// `.length` per app rather than a flatMap: the four families return four
			// different descriptor types, and a union of arrays does not flatten.
			const declared = examples.reduce(
				(n, b) => n + family.cli(b.spec).length,
				0,
			)
			expect(
				declared,
				`no corpus app declares a ${family.name}`,
			).toBeGreaterThan(0)
		}
	})
})
