/**
 * Jobs — the durable background-job runtime and the declared-recurrence
 * scheduler behind the `jobs` bundle.
 *
 * `JobQueue` is the runtime: retries with backoff, dead-lettering, and an
 * idempotency key the database enforces. `Scheduler` is the bridge from the
 * spec's declared schedules to it — one job per occurrence, keyed, so restarts
 * and multiple workers cannot double-fire. The handler slot the scheduler calls
 * (`ScheduleHandler`) is generated by `@maxstack/core`'s ownership layer and
 * owned by the user.
 *
 * Delivery is **at-least-once**. See `service.ts`.
 */

export { createDrizzleJobStore } from './drizzle-store.ts'
export type {
	ScheduledJobPayload,
	ScheduleHandlerOptions,
	ScheduleOccurrence,
	SchedulerOptions,
	ScheduleTick,
} from './scheduler.ts'
export {
	occurrenceKey,
	registerScheduleHandlers,
	SCHEDULED_JOB_TYPE,
	Scheduler,
	schedulesOf,
} from './scheduler.ts'
export { JOBS_DDL, job } from './schema.ts'
export type {
	EnqueueInput,
	JobHandler,
	JobHandlerContext,
	JobRecord,
	JobStatus,
	JobStore,
	ScheduleHandler,
	ScheduleHandlerContext,
} from './service.ts'
export {
	backoffMs,
	createMemoryJobStore,
	DuplicateIdempotencyKeyError,
	isUniqueViolation,
	JobQueue,
	PermanentJobError,
	scheduleInterval,
} from './service.ts'
