/**
 * The PreToolUse guard — the enforcement half of "grow the app by changing the
 * spec". Prose told agents that and they hand-wrote routes anyway; this denies
 * the write. The tests pin both directions, because a guard that over-denies
 * strands a session just as badly as one that under-denies.
 */

import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { denialReason, type HookEvent } from './guard.ts'

/** Run the decision over a synthetic PreToolUse event. `null` means allow. */
const probe = (event: Record<string, unknown>): Promise<string | null> =>
	denialReason(event as HookEvent)

describe('guard-edit (PreToolUse)', () => {
	let dir: string
	const write = (path: string) => ({
		tool_name: 'Write',
		tool_input: { file_path: join(dir, path) },
		cwd: dir,
	})

	beforeAll(async () => {
		dir = await mkdtemp(join(tmpdir(), 'maxstack-guard-'))
		await writeFile(
			join(dir, 'maxstack.json'),
			JSON.stringify({ appDir: 'app' }),
		)
		await mkdir(join(dir, 'app', 'routes'), { recursive: true })
		await writeFile(
			join(dir, 'app', '.generated.routes.json'),
			JSON.stringify({
				version: 1,
				entries: [
					{
						id: 'book',
						routePath: '/book',
						file: 'routes/book.tsx',
						ownership: 'generated',
					},
					{
						id: 'story',
						routePath: '/story',
						file: 'routes/story.tsx',
						slotFile: 'routes/story.slots.tsx',
						ownership: 'generated',
					},
					{
						id: 'story:slot',
						routePath: '',
						file: 'routes/story.slots.tsx',
						ownership: 'user',
					},
					{
						id: 'owned',
						routePath: '/owned',
						file: 'routes/owned.tsx',
						ownership: 'ejected',
					},
				],
			}),
		)
	})

	afterAll(async () => {
		await rm(dir, { recursive: true, force: true })
	})

	it('denies a generated route and names the spec + eject paths', async () => {
		const reason = await probe(write('app/routes/book.tsx'))
		expect(reason).toContain('overwritten on every regeneration')
		expect(reason).toContain('apply_spec_change')
		expect(reason).toContain('maxstack eject book')
		// No slot on this entry, so it must not invent one.
		expect(reason).not.toContain('.slots.tsx')
		expect(reason).toContain('Two supported ways')
	})

	it('offers the slot first when the route has one', async () => {
		const reason = await probe(write('app/routes/story.tsx'))
		expect(reason).toContain('app/routes/story.slots.tsx')
		expect(reason).toContain('Three supported ways')
	})

	it('allows the slot file itself — it is user-owned', async () => {
		expect(await probe(write('app/routes/story.slots.tsx'))).toBeNull()
	})

	it('allows an ejected route', async () => {
		expect(await probe(write('app/routes/owned.tsx'))).toBeNull()
	})

	it('denies the files the generator rewrites wholesale', async () => {
		expect(await probe(write('app/routes.ts'))).toContain('regenerated')
		expect(await probe(write('app/.generated.routes.json'))).toContain(
			'regenerated',
		)
		expect(await probe(write('app/owned.generated.tsx'))).toContain(
			'regenerated',
		)
	})

	it('allows everything outside the app dir', async () => {
		expect(await probe(write('spec/data.json'))).toBeNull()
		expect(await probe(write('README.md'))).toBeNull()
	})

	it('allows a new file the manifest does not know about', async () => {
		// The generator has no claim on it, so the agent may create it.
		expect(await probe(write('app/routes/brand-new.tsx'))).toBeNull()
	})

	it('ignores non-editing tools', async () => {
		expect(
			await probe({
				tool_name: 'Bash',
				tool_input: { file_path: join(dir, 'app/routes/book.tsx') },
				cwd: dir,
			}),
		).toBeNull()
	})

	it('falls open on anything unexpected', async () => {
		// A guard that throws would brick every edit in the project, so a
		// malformed payload, a missing path, and a non-maxstack directory must
		// all allow the write rather than deny it.
		expect(await probe({ nonsense: true })).toBeNull()
		expect(await probe({ tool_name: 'Write', tool_input: {} })).toBeNull()
		expect(
			await probe({
				tool_name: 'Write',
				tool_input: { file_path: '/tmp/unrelated-xyz.txt' },
				cwd: '/tmp',
			}),
		).toBeNull()
	})

	it('denies an unmanifested file that declares itself generated', async () => {
		// The banner is the weaker fallback for when the manifest can't identify
		// a file; it only ever adds denials.
		await writeFile(
			join(dir, 'app', 'routes', 'stray.tsx'),
			'// AUTO-GENERATED by maxstack — DO NOT EDIT.\nexport default null\n',
		)
		expect(await probe(write('app/routes/stray.tsx'))).toContain('DO NOT EDIT')
	})
})
