/**
 * `maxstack guard-edit` — the PreToolUse hook that keeps an agent on the spec.
 *
 * Docs tell an agent to grow the app by changing the spec; nothing made it true.
 * A dogfood session read the briefing, looked at the generated page, and went
 * straight to hand-writing a route — the one move every layer of prose forbids.
 * Prose is advisory; a hook is not. This runs *before* Write/Edit lands and
 * denies edits to framework-owned files, naming the two legitimate ways
 * forward (fill the slot, or eject) so the refusal is a redirect, not a wall.
 *
 * Wire-up lives in the scaffolded `.claude/settings.json`. It speaks the
 * PreToolUse contract: event JSON on stdin, a `permissionDecision` on stdout.
 *
 * **It fails open, always.** A guard that throws would brick every edit in the
 * project. Anything unexpected — not a maxstack project, unreadable manifest,
 * malformed payload — allows the write and stays silent. Its job is to catch
 * the confident-but-wrong edit, not to be a gate that can strand a session.
 */

import { readFile } from 'node:fs/promises'
import { isAbsolute, relative, resolve } from 'node:path'
import { parseManifest, type RouteManifest } from '@maxstack/core/ownership'
import { CONFIG_FILENAME, DEFAULT_CONFIG } from '../lib/project.ts'

/** Files the generator rewrites wholesale, regardless of the manifest. */
const ALWAYS_GENERATED = new Set([
	'routes.ts', // rewritten by addRouteToManifest on every page add
	'.generated.routes.json', // the manifest itself
	'owned.generated.tsx', // re-emitted on every build/dev boot
])

const MANIFEST_FILENAME = '.generated.routes.json'

export interface HookEvent {
	tool_name?: string
	tool_input?: { file_path?: string }
	cwd?: string
}

export async function guardEditCommand(): Promise<void> {
	try {
		const reason = await denialReason(await readEvent())
		if (reason) {
			process.stdout.write(
				`${JSON.stringify({
					hookSpecificOutput: {
						hookEventName: 'PreToolUse',
						permissionDecision: 'deny',
						permissionDecisionReason: reason,
					},
				})}\n`,
			)
		}
	} catch {
		// Fail open — see the module note.
	}
}

async function readEvent(): Promise<HookEvent> {
	const chunks: Buffer[] = []
	for await (const chunk of process.stdin) chunks.push(chunk as Buffer)
	return JSON.parse(Buffer.concat(chunks).toString('utf8')) as HookEvent
}

/**
 * The message to deny with, or null to allow — the whole decision, kept pure so
 * it can be tested without mocking stdio.
 */
export async function denialReason(event: HookEvent): Promise<string | null> {
	const tool = event.tool_name ?? ''
	if (!['Write', 'Edit', 'NotebookEdit'].includes(tool)) return null

	const target = event.tool_input?.file_path
	if (!target) return null

	const cwd = event.cwd ?? process.cwd()
	const absolute = isAbsolute(target) ? target : resolve(cwd, target)

	const root = await findProjectRoot(cwd)
	if (!root) return null

	const appDir = await readAppDir(root)
	const rel = relative(resolve(root, appDir), absolute)
	// Outside the generated tree (or above it) — not ours to police.
	if (rel.startsWith('..') || isAbsolute(rel)) return null
	const path = rel.split('\\').join('/')

	if (ALWAYS_GENERATED.has(path)) {
		return (
			`\`${appDir}/${path}\` is regenerated by maxstack — editing it will be ` +
			`overwritten.\n\nChange the spec instead (\`mcp__maxstack__apply_spec_change\`, ` +
			`or \`maxstack add-entity\` / \`add-page\`), then regenerate.`
		)
	}

	const manifest = await readManifest(resolve(root, appDir))
	if (!manifest) return bannerFallback(absolute, appDir, path)

	const entry = manifest.entries.find((e) => e.file === path)
	if (!entry) return bannerFallback(absolute, appDir, path)
	// The user owns these outright — slot files and ejected routes.
	if (entry.ownership !== 'generated') return null

	const slot = entry.slotFile
	return (
		`\`${appDir}/${path}\` is generated from the spec and is overwritten on every ` +
		`regeneration — your edit would be silently lost.\n\n` +
		`${slot ? 'Three' : 'Two'} supported ways to change it:\n` +
		(slot
			? `1. **Fill the slot** — edit \`${appDir}/${slot}\`. It is yours, survives ` +
				`regeneration, and is the right home for custom rendering.\n`
			: '') +
		`${slot ? '2.' : '1.'} **Change the spec** — \`mcp__maxstack__apply_spec_change\` ` +
		`(or \`maxstack add-field\` / \`add-page\`), then regenerate. This is the ` +
		`default: the page follows the spec and keeps improving with the framework.\n` +
		`${slot ? '3.' : '2.'} **Take the whole file** — \`maxstack eject ${entry.id}\` ` +
		`(\`--dry-run\` to preview). After that it is yours, but it stops tracking ` +
		`spec changes and you maintain it by hand. Reach for this only when the spec ` +
		`genuinely cannot express what you need.`
	)
}

/**
 * Last resort when the manifest can't identify the file: trust the emitted
 * banner. Deliberately weaker than the manifest — an ejected route whose
 * destination equalled its source keeps no banner at all — so it only ever adds
 * denials for files that self-identify as generated.
 */
async function bannerFallback(
	absolute: string,
	appDir: string,
	path: string,
): Promise<string | null> {
	try {
		const head = (await readFile(absolute, 'utf8')).slice(0, 400)
		if (!head.includes('DO NOT EDIT')) return null
		return (
			`\`${appDir}/${path}\` is marked DO NOT EDIT — maxstack regenerates it ` +
			`and your change would be lost.\n\nChange the spec instead ` +
			`(\`mcp__maxstack__apply_spec_change\`), or run \`maxstack eject\` to take ` +
			`ownership of the route first.`
		)
	} catch {
		// New file, or unreadable: nothing claims it's generated.
		return null
	}
}

/** Walk up for `maxstack.json`, bounded like the runtime's own resolver. */
async function findProjectRoot(from: string): Promise<string | null> {
	let dir = resolve(from)
	for (let i = 0; i < 6; i++) {
		try {
			await readFile(resolve(dir, CONFIG_FILENAME), 'utf8')
			return dir
		} catch {
			const parent = resolve(dir, '..')
			if (parent === dir) return null
			dir = parent
		}
	}
	return null
}

async function readAppDir(root: string): Promise<string> {
	try {
		const config = JSON.parse(
			await readFile(resolve(root, CONFIG_FILENAME), 'utf8'),
		) as { appDir?: string }
		return config.appDir ?? DEFAULT_CONFIG.appDir
	} catch {
		return DEFAULT_CONFIG.appDir
	}
}

async function readManifest(appPath: string): Promise<RouteManifest | null> {
	try {
		return parseManifest(
			await readFile(resolve(appPath, MANIFEST_FILENAME), 'utf8'),
		)
	} catch {
		return null
	}
}
