import {
	createMemFs,
	MANIFEST_FILENAME,
	ownershipDrift,
} from '@maxstack/core/ownership'
import type { SpecSystem } from '@maxstack/spec'
import { minimalPRD, newSpecSystem } from '@maxstack/spec'
import { describe, expect, it } from 'vitest'
import { regenTargets } from './ownership.ts'

/**
 * The current derivation, across every family the generator emits.
 *
 * The property under test is not "the registries are emitted" — it is that a
 * maintainer who ejects one is told what it is behind, instead of being told the
 * page it came from was deleted. It never came from a page.
 */

function base(): SpecSystem {
	return newSpecSystem(
		minimalPRD({
			title: 'Crmlite',
			tldr: 'Contacts and the mail about them.',
			problem: 'Threads live in one inbox and nowhere else.',
			northStar: 'Contacts with a synced thread',
			persona: 'Solo founder',
			differentiation: 'The inbox is the CRM.',
		}),
	)
}

/**
 * A spec with one of each declared seam. Only the fields the descriptor folds
 * actually read are populated — this exercises the derivation, not the
 * validator, and building four fully-valid declarations here would test the spec
 * layer's shape rather than this module's fold.
 */
function withEverySeam(): SpecSystem {
	return {
		...base(),
		schedules: {
			schedules: [
				{
					key: 'invoice.recurring',
					description: 'Issue recurring invoices',
					timezone: 'America/New_York',
					recurrence: { kind: 'monthly', onDayOfMonth: 1, atTime: '09:00' },
					runAs: { kind: 'service', role: 'billing' },
				},
			],
		},
		sources: {
			sources: [
				{
					key: 'inbox.sync',
					description: 'Sync the shared inbox',
					mode: 'sync',
					request: { url: 'https://api.example.com/messages?since=1' },
					refine: true,
				},
			],
		},
		imports: {
			importers: [
				{
					key: 'anki.apkg',
					description: 'Import an Anki deck',
					format: 'custom',
					entityId: 'e-card',
				},
			],
		},
		live: {
			subscriptions: [
				{
					key: 'task-board',
					description: 'The live board',
					kind: 'query',
					entityId: 'e-task',
					scope: { kind: 'all' },
					fields: [],
					slot: true,
				},
			],
		},
	} as unknown as SpecSystem
}

describe('regenTargets', () => {
	it('derives the framework-owned registry of every declared seam', () => {
		const ids = regenTargets(withEverySeam()).map((t) => t.id)
		expect(ids).toContain('schedules:registry')
		expect(ids).toContain('sources:registry')
		expect(ids).toContain('imports:registry')
		expect(ids).toContain('live:registry')
	})

	it('derives the registry content the generator would write', () => {
		const target = regenTargets(withEverySeam()).find(
			(t) => t.id === 'schedules:registry',
		)
		expect(target?.file).toBe('jobs/schedules.generated.ts')
		expect(target?.nextContent).toContain("'invoice.recurring'")
		expect(target?.nextContent).toContain('GENERATED by maxstack')
	})

	it('emits no registry for a seam nothing declares — the absence rule', () => {
		// A project that never declared a schedule must not get an empty registry
		// as its "current derivation": everything owned under that id would then
		// read as drifted by its entire contents.
		expect(regenTargets(base()).map((t) => t.id)).toEqual([])
	})

	it('emits nothing for a declaration that opened no seam', () => {
		const spec = withEverySeam()
		const noSeams = {
			...spec,
			sources: {
				sources: [{ ...spec.sources?.sources?.[0], refine: false }],
			},
			imports: {
				importers: [{ ...spec.imports?.importers?.[0], format: 'csv' }],
			},
			live: {
				subscriptions: [{ ...spec.live?.subscriptions?.[0], slot: false }],
			},
		} as unknown as SpecSystem
		const ids = regenTargets(noSeams).map((t) => t.id)
		expect(ids).toContain('schedules:registry')
		expect(ids).not.toContain('sources:registry')
		expect(ids).not.toContain('imports:registry')
		expect(ids).not.toContain('live:registry')
	})

	it('makes an ejected registry comparable instead of underived', async () => {
		const spec = withEverySeam()
		const target = regenTargets(spec).find((t) => t.id === 'schedules:registry')
		if (!target) throw new Error('no schedule registry derived')

		const fs = createMemFs()
		// The maintainer ejected it and hand-edited it.
		await fs.write(target.file, `${target.nextContent}\n// mine now\n`)
		await fs.write(MANIFEST_FILENAME, '{"version":1,"entries":[]}')

		const report = await ownershipDrift(
			fs,
			{
				version: 1,
				entries: [
					{
						id: 'schedules:registry',
						routePath: '',
						file: target.file,
						ownership: 'ejected',
					},
				],
			},
			regenTargets(spec),
		)
		expect(report.owned[0]?.status).toBe('drifted')
		expect(report.owned[0]?.family).toBe('schedule')
		expect(report.owned[0]?.patch).toContain('mine now')
	})
})
