/**
 * Generator-side emission via ts-morph.
 *
 * Every prior generation spliced code with brittle string surgery —
 * `source.replace('pages: []', …)` — which corrupts the file the moment the
 * anchor string shifts, appears twice, or lands inside a comment. This module
 * is the fix the archive designed (aiwf `ts-morph-implementation.md`) but never
 * wired in: routes are inserted into the manifest array through the AST, so the
 * edit is structural, idempotent, and can't scramble surrounding code.
 *
 * `addRouteToManifest` is the concrete "replace one string-.replace() codegen
 * path with a ts-morph transform" deliverable. `emitResourcePage` is the
 * generator that produces a slot-bearing route module.
 */

import {
	IndentationText,
	Project,
	QuoteKind,
	SyntaxKind,
	VariableDeclarationKind,
} from 'ts-morph'

/** Everything the page generator needs. Derived upstream from a Sprout resource. */
export interface PageDescriptor {
	/** Resource id, e.g. `task`. Drives file names and the manifest id. */
	resource: string
	/** Plural human label rendered as the page heading, e.g. `Tasks`. */
	title: string
	/** The app route path, e.g. `/admin/tasks`. */
	routePath: string
	/**
	 * Named extension slots the generated page exposes. Each becomes a
	 * `<Slot name=… render={slots.<name>} />` composed from the user-owned slot
	 * file. This is the cross-file extension seam — part-generated,
	 * part-hand-written at the module boundary, no AST merge.
	 */
	slots: string[]
}

const BANNER = [
	'// AUTO-GENERATED by maxstack — DO NOT EDIT.',
	'// Owned by the framework; regeneration overwrites this file. To take',
	'// ownership run `maxstack eject <id>`. Customize without ejecting by',
	'// filling the user-owned slot file this page composes from.',
].join('\n')

/** The block-`type` prefix marking a page block as a named extension slot. */
const SLOT_TYPE_PREFIX = 'slot:'

/**
 * Whether a block's `type` marks it as a named extension slot (`slot:<name>`).
 * Only these blocks get a `<Slot>` in the generated route and a render-fn stub
 * in the user-owned slot file — other template blocks (`table`, `form`, …)
 * have no runtime slot seam.
 */
export function isSlotBlockType(type: string): boolean {
	return type.startsWith(SLOT_TYPE_PREFIX)
}

/**
 * The ONE canonical slot name, shared by route generation (`pageDescriptor`)
 * and the live runtime (`project-routes.ts`'s `getRoutes`): the `<name>` suffix
 * of a `slot:<name>` block type. Before issue #42 the generator instead named
 * slots from the block `id`, so a filled slot only worked when a block's id
 * happened to stem-match its own type suffix.
 */
export function slotBlockName(type: string): string {
	return type.slice(SLOT_TYPE_PREFIX.length)
}

/**
 * The slot name a block's `id` alone would have implied under the pre-#42
 * derivation (`blk-pack-loadout` → `pack_loadout`). No longer used to name
 * anything — kept only so `validate` can flag a `slot:` block whose id reads
 * as a different slot than its type declares, which is almost always a
 * copy-paste mistake worth surfacing even though it no longer breaks the app.
 */
export function slotIdHint(blockId: string): string {
	const stem = blockId.replace(/^blk-/, '').replace(/[^a-zA-Z0-9]/g, '_')
	return /^[a-zA-Z_]/.test(stem) ? stem : `s_${stem}`
}

/** `task` → `TaskListPage`. */
function pageComponentName(resource: string): string {
	const pascal = resource
		.split(/[_\-\s]+/)
		.filter(Boolean)
		.map((w) => w.charAt(0).toUpperCase() + w.slice(1))
		.join('')
	return `${pascal}ListPage`
}

/** Repo-relative-ish module specifier the page imports its slot file by. */
export function slotModuleSpecifier(resource: string): string {
	return `./${resource}.slots.tsx`
}

function newProject(): Project {
	return new Project({
		useInMemoryFileSystem: true,
		manipulationSettings: {
			indentationText: IndentationText.Tab,
			quoteKind: QuoteKind.Single,
		},
	})
}

/**
 * Emit the route module for a resource: a heading, a placeholder for the
 * generated list, and one `<Slot>` per declared slot rendering from the
 * user-owned slot file. Deterministic — the same descriptor always yields
 * byte-identical output, which is what makes regeneration-as-diff meaningful.
 */
export function emitResourcePage(descriptor: PageDescriptor): string {
	const { resource, title, slots } = descriptor
	const component = pageComponentName(resource)
	const project = newProject()
	const sf = project.createSourceFile(`${resource}.tsx`)

	// Both imports are conditional on the page actually declaring slots: `<Slot>`
	// is only ever emitted by `slotJsx` below, which is empty at zero slots. An
	// unconditional import left every slotless page — the default — with a dead
	// import in a file stamped DO-NOT-EDIT, so the moment a scaffold runs a
	// linter (`noUnusedImports` is on by default in Biome) the user's own gate
	// went red on framework-owned code they cannot fix without ejecting.
	if (slots.length > 0) {
		sf.addImportDeclaration({
			moduleSpecifier: '@maxstack/ui',
			namedImports: ['Slot'],
		})
		sf.addImportDeclaration({
			moduleSpecifier: slotModuleSpecifier(resource),
			namespaceImport: 'slots',
		})
	}

	sf.addVariableStatement({
		isExported: true,
		declarationKind: VariableDeclarationKind.Const,
		declarations: [
			{
				name: 'meta',
				initializer: `{ resource: '${resource}', generated: true }`,
			},
		],
	})

	const slotJsx = slots
		.map((name) => `\t\t\t<Slot name="${name}" render={slots.${name}} />`)
		.join('\n')
	const body = [
		'return (',
		`\t\t<section data-resource="${resource}">`,
		`\t\t\t<h1>${title}</h1>`,
		'\t\t\t{/* generated resource list renders here */}',
		slotJsx,
		'\t\t</section>',
		'\t)',
	]
		.filter(Boolean)
		.join('\n')

	const fn = sf.addFunction({
		name: component,
		isExported: true,
		isDefaultExport: true,
	})
	fn.setBodyText(body)

	// Normalize to Biome-ish style: tabs, no semicolons.
	sf.formatText({ indentSize: 1, convertTabsToSpaces: false })
	const printed = sf.getFullText().replace(/;\n/g, '\n').replace(/;$/gm, '')
	return `${BANNER}\n${printed.startsWith('\n') ? printed.slice(1) : printed}`
}

/**
 * Emit the ONE-TIME user-owned slot stub. Written only when the file is absent
 * (never-clobber): once the user edits it, the generator must never touch it
 * again. Each declared slot gets an exported render function returning null so
 * the page typechecks and renders before the user fills anything in.
 */
export function emitUserSlotStub(descriptor: PageDescriptor): string {
	const { slots } = descriptor
	const fns = slots
		.map((name) =>
			[
				`// Fill in your ${name} content. This file is yours — the`,
				'// generator created it once and will never overwrite it.',
				`export function ${name}() {`,
				// Deliberately not `null`. An exported stub is already registered in
				// OWNED_SLOTS, so a `mode: "replace"` slot suppresses the default list
				// the moment it is scaffolded — and a stub returning null then left
				// the page completely blank, with nothing to say why. A visible
				// placeholder keeps the page self-explanatory between scaffolding and
				// implementation, and it disappears the moment real content lands.
				`\treturn <p>Slot \`${name}\` — implement this in this file.</p>`,
				'}',
			].join('\n'),
		)
		.join('\n\n')
	return `${fns}\n`
}

/**
 * The names a slot file already exports, via the AST (so a user who renamed,
 * reformatted, or wrapped a stub is still recognized). Covers `export function
 * f() {}` and `export const f = …` — the two shapes a slot render fn takes.
 */
export function exportedSlotNames(source: string): string[] {
	const project = newProject()
	const sf = project.createSourceFile('slots.tsx', source)
	const names = new Set<string>()
	for (const fn of sf.getFunctions()) {
		if (fn.isExported()) {
			const name = fn.getName()
			if (name) names.add(name)
		}
	}
	for (const stmt of sf.getVariableStatements()) {
		if (!stmt.isExported()) continue
		for (const decl of stmt.getDeclarations()) names.add(decl.getName())
	}
	return [...names]
}

/**
 * Given the current slot-file content, emit the render-fn stubs for any declared
 * slots that aren't exported yet — the append-only "scaffold a newly-added slot"
 * payload. Returns the stub text (empty when nothing is missing) and the slot
 * names it covers, so the writer can append without touching existing content.
 * This closes the task-9 gap where a slot added to a live page left its
 * `render={slots.X}` reference dangling.
 */
export function emitMissingSlotStubs(
	source: string,
	descriptor: PageDescriptor,
): { stubs: string; added: string[] } {
	const have = new Set(exportedSlotNames(source))
	const added = descriptor.slots.filter((name) => !have.has(name))
	if (added.length === 0) return { stubs: '', added }
	return { stubs: emitUserSlotStub({ ...descriptor, slots: added }), added }
}

export interface RouteEntryLiteral {
	path: string
	file: string
}

/** The `path:` of a route array element, for canonical ordering. */
function elementPath(text: string): string {
	return /path:\s*'([^']*)'/.exec(text)?.[1] ?? text
}

/**
 * AST-insert a route into a `routes.ts` manifest — the ts-morph transform that
 * replaces `source.replace('pages: []', …)`. Finds `export const routes = [`,
 * inserts `{ path, file }` if a route with that `path` isn't already present
 * (idempotent), and returns the reprinted source. Because it operates on the
 * array node, it is immune to the anchor-string fragility that broke every
 * generation's string splice.
 *
 * The array is kept sorted **by route path** rather than in insertion order
 *. These are distinct static paths, so matching does not depend on
 * their sequence — but generation order does, and generation order is install
 * order. Appending would mean two developers who added the same bundles in a
 * different sequence get different `routes.ts` bytes, and every diff between
 * them is noise. Canonical order makes the file a function of *what* is
 * installed rather than of *when* each part was.
 *
 * The seed manifest ({@link EMPTY_ROUTES_MANIFEST}) is what a fresh project
 * starts from.
 */
export function addRouteToManifest(
	source: string,
	entry: RouteEntryLiteral,
): string {
	const project = new Project({
		useInMemoryFileSystem: true,
		manipulationSettings: {
			indentationText: IndentationText.Tab,
			quoteKind: QuoteKind.Single,
		},
	})
	const sf = project.createSourceFile('routes.ts', source)

	const decl = sf.getVariableDeclarationOrThrow('routes')
	const array = decl.getInitializerIfKindOrThrow(
		SyntaxKind.ArrayLiteralExpression,
	)

	const existing = array.getElements().map((el) => el.getText())
	const already = existing.some((text) =>
		text.includes(`path: '${entry.path}'`),
	)
	const next = already
		? existing
		: [...existing, `{ path: '${entry.path}', file: '${entry.file}' }`]
	const sorted = [...next].sort((a, b) =>
		elementPath(a).localeCompare(elementPath(b)),
	)
	// Rewrite only when something actually moved — an untouched manifest must
	// come back byte-identical, since `generateResourcePage` writes on inequality.
	if (already && sorted.every((text, i) => text === existing[i])) return source
	array.replaceWithText(`[${sorted.join(', ')}]`)

	sf.formatText({ indentSize: 1, convertTabsToSpaces: false })
	return sf.getFullText().replace(/;\n/g, '\n').replace(/;$/gm, '')
}

export const EMPTY_ROUTES_MANIFEST = `export const routes = []\n`
