import { describe, expect, it } from 'vitest'
import {
	addRouteToManifest,
	EMPTY_ROUTES_MANIFEST,
	emitResourcePage,
	emitUserSlotStub,
	isMaterializedPage,
	type PageDescriptor,
	type PageListSurface,
	UNMATERIALIZED_MARKER,
} from './emit.ts'
import { generateResourcePage, pageFilePaths } from './generate.ts'
import {
	emptyManifest,
	generationWatermark,
	hashContent,
	MANIFEST_FILENAME,
	parseManifest,
	recordGeneration,
	serializeManifest,
	upsertEntry,
} from './manifest.ts'
import { createMemFs } from './memfs.ts'
import {
	applyReviewedDiff,
	checkProvenanceInvariants,
	checkRegenSafety,
	type FsSnapshot,
	type RegenTarget,
	regenerateAsDiff,
} from './regen.ts'
import { EJECT_BANNER, eject, writeGenerated, writeOwned } from './write.ts'

const TASK: PageDescriptor = {
	resource: 'task',
	title: 'Tasks',
	routePath: '/admin/tasks',
	slots: ['afterList'],
}

describe('emit (ts-morph generator-side emission)', () => {
	it('emits a slot-bearing route module with the generated banner', () => {
		const src = emitResourcePage(TASK)
		expect(src).toContain('AUTO-GENERATED by maxstack')
		expect(src).toContain("import { Slot } from '@maxstack/ui'")
		expect(src).toContain("import * as slots from './task.slots.tsx'")
		expect(src).toContain('<Slot name="afterList" render={slots.afterList} />')
		expect(src).toContain('export default function TaskListPage()')
		// Biome style: no semicolons survive the emit.
		expect(src).not.toMatch(/;\s*$/m)
	})

	it('omits the Slot import entirely when the page declares no slots', () => {
		// A slotless page is the default shape, and `<Slot>` is only emitted by
		// slotJsx — so an unconditional import is dead code in a DO-NOT-EDIT file.
		// The moment the scaffold runs a linter, `noUnusedImports` reddens the
		// user's gate on framework-owned code they are told not to edit.
		const src = emitResourcePage({ ...TASK, slots: [] })
		expect(src).not.toContain('Slot')
		expect(src).not.toContain('@maxstack/ui')
		expect(src).not.toContain('import')
		// The page itself still emits.
		expect(src).toContain('export default function TaskListPage()')
		// …and a slotted page keeps both imports.
		const slotted = emitResourcePage(TASK)
		expect(slotted).toContain("import { Slot } from '@maxstack/ui'")
		expect(slotted).toContain("import * as slots from './task.slots.tsx'")
	})

	it('never emits an import binding the module does not use', () => {
		// Generic guard so the next unconditional import cannot land the same way.
		// Swept across the list variants too (#349): each pulls a different
		// component out of `@maxstack/ui`, so this is where an emitter that
		// imports `ResourceList` and renders `CardGrid` gets caught.
		const surfaces: (PageListSurface | undefined)[] = [
			undefined,
			{ variant: 'table' },
			{ variant: 'cards', fields: ['title'] },
			{ variant: 'feed' },
		]
		for (const slots of [[], ['afterList'], ['afterList', 'beforeList']]) {
			for (const list of surfaces) {
				const src = emitResourcePage({
					...TASK,
					slots,
					...(list ? { list } : {}),
				})
				const lines = src.split('\n')
				const bindings = lines.flatMap((line) => {
					const named = /^import \{ ([^}]+) \} from /.exec(line)
					// `type X` is one binding written two words; the name is what the
					// body has to mention.
					if (named?.[1])
						return named[1]
							.split(',')
							.map((n) => n.trim().replace(/^type /, ''))
					const ns = /^import \* as (\w+) from /.exec(line)
					return ns?.[1] ? [ns[1]] : []
				})
				const body = lines
					.filter((line) => !line.startsWith('import '))
					.join('\n')
				for (const binding of bindings) {
					expect(
						new RegExp(`\\b${binding}\\b`).test(body),
						`unused import \`${binding}\` at slots=[${slots.join(',')}] variant=${list?.variant ?? 'none'}`,
					).toBe(true)
				}
			}
		}
	})

	/**
	 * Issue #349. `maxstack eject` is the escape hatch, and what it handed over
	 * was a heading, a comment and the slot mounts — 17 lines that had never
	 * rendered the user's page. The page came from the runtime's own
	 * `project.page.tsx`, resolving the spec at request time, and it kept coming
	 * from there after the eject.
	 *
	 * These assert the emitted module is the page: it takes the loader's output
	 * as props and renders the declared list from them.
	 */
	describe('materialized list surface (#349)', () => {
		const LIST: PageDescriptor = { ...TASK, list: { variant: 'table' } }

		it('renders the real list from the props the runtime hands down', () => {
			const src = emitResourcePage(LIST)
			// The failing-before-#349 assertion: the module takes props at all.
			expect(src).toContain(
				'export default function TaskListPage({\n\tlist,\n\tnewHref,\n\ttoolbar,\n\tLink,\n}: OwnedRouteProps)',
			)
			expect(src).toContain('<ResourceList {...list} />')
			// The control bar reaches the ejected page too (#342). Without this
			// line an ejected list silently loses search, filters and export —
			// which is how the generated app came to be a second-class citizen of
			// its own component library in the first place.
			expect(src).toContain('{toolbar}')
			expect(src).toContain('type OwnedRouteProps')
			// …and the placeholder that stood in for the page is gone.
			expect(src).not.toContain('generated resource list renders here')
			expect(src).not.toContain(UNMATERIALIZED_MARKER)
			expect(isMaterializedPage(src)).toBe(true)
		})

		it('gives the page its own header and "+ New" affordance', () => {
			// An ejected module replaces the framework's whole surface, header
			// included. Emitting the list alone would silently drop the only way to
			// create a record on a page the user was told they now own.
			const src = emitResourcePage(LIST)
			expect(src).toContain('<h1 className="text-2xl font-semibold">Tasks</h1>')
			expect(src).toContain('to={newHref}')
			expect(src).toContain('+ New')
		})

		it('inlines the declared fields for the card and feed variants', () => {
			// The spec-derived half, as a literal in a file the user owns — no
			// `resolveProjectResource` at render time for this decision.
			const cards = emitResourcePage({
				...TASK,
				list: { variant: 'cards', fields: ['title', 'due'] },
			})
			expect(cards).toContain("const LIST_FIELDS = ['title', 'due']")
			expect(cards).toContain('<CardGrid')
			expect(cards).toContain('primaryField={LIST_FIELDS[0]}')
			expect(cards).toContain('secondaryFields={LIST_FIELDS}')
			expect(cards).not.toContain('ResourceList')

			const feed = emitResourcePage({ ...TASK, list: { variant: 'feed' } })
			expect(feed).toContain('<FeedList {...list} />')
			// No declared fields ⇒ no literal, rather than an empty one.
			expect(feed).not.toContain('LIST_FIELDS')
		})

		it('says so, in the file, when the surface cannot be materialized', () => {
			// A view page (calendar/timeline/board) has no `list`. Ejecting one
			// trades a working board for this stub, so the file names the trade
			// rather than looking like an ordinary page that happens to be empty.
			const src = emitResourcePage(TASK)
			expect(isMaterializedPage(src)).toBe(false)
			expect(src).toContain(UNMATERIALIZED_MARKER)
			expect(src).toContain('placeholder, not the page')
			// No props: a placeholder that destructured them would trip the
			// scaffold's own unused-binding lint.
			expect(src).toContain('export default function TaskListPage()')
		})

		it('keeps the note where eject cannot strip it', async () => {
			// `eject()` drops the leading comment block when it swaps in its own
			// banner. A header comment would therefore vanish at exactly the moment
			// the warning matters, so it lives in the JSX.
			const fs = createMemFs()
			const { manifest } = await generateResourcePage(fs, TASK)
			const routeFile = pageFilePaths('task').routeFile
			await eject(fs, manifest, 'task', routeFile)
			const after = await fs.read(routeFile)
			expect(after).toContain('EJECTED')
			expect(after).not.toContain('AUTO-GENERATED')
			expect(after).toContain(UNMATERIALIZED_MARKER)
		})

		it('is deterministic across every variant', () => {
			for (const list of [
				{ variant: 'table' as const },
				{ variant: 'cards' as const, fields: ['a', 'b'] },
				{ variant: 'feed' as const },
			]) {
				const d = { ...TASK, list }
				expect(emitResourcePage(d)).toBe(emitResourcePage(d))
			}
		})
	})

	it('is deterministic — same descriptor yields byte-identical output', () => {
		expect(emitResourcePage(TASK)).toBe(emitResourcePage(TASK))
	})

	it('emits a user slot stub with one render fn per slot', () => {
		const stub = emitUserSlotStub(TASK)
		expect(stub).toContain('export function afterList()')
		// Deliberately renders something rather than null: an exported stub is
		// already live in OWNED_SLOTS, so a `mode: "replace"` slot suppresses the
		// default list as soon as it's scaffolded. Returning null left the page
		// blank with no explanation.
		expect(stub).not.toContain('return null')
		expect(stub).toContain('implement this in this file')
	})

	describe('addRouteToManifest (replaces the string .replace() splice)', () => {
		it('inserts a route through the AST', () => {
			const out = addRouteToManifest(EMPTY_ROUTES_MANIFEST, {
				path: '/admin/tasks',
				file: './routes/task.tsx',
			})
			expect(out).toContain("path: '/admin/tasks'")
			expect(out).toContain("file: './routes/task.tsx'")
		})

		it('is idempotent — re-inserting the same path is a no-op', () => {
			const once = addRouteToManifest(EMPTY_ROUTES_MANIFEST, {
				path: '/admin/tasks',
				file: './routes/task.tsx',
			})
			const twice = addRouteToManifest(once, {
				path: '/admin/tasks',
				file: './routes/task.tsx',
			})
			expect(twice).toBe(once)
			expect(twice.match(/\/admin\/tasks/g)).toHaveLength(1)
		})

		it('appends a second distinct route without disturbing the first', () => {
			let out = addRouteToManifest(EMPTY_ROUTES_MANIFEST, {
				path: '/admin/tasks',
				file: './routes/task.tsx',
			})
			out = addRouteToManifest(out, {
				path: '/admin/tags',
				file: './routes/tag.tsx',
			})
			expect(out).toContain('/admin/tasks')
			expect(out).toContain('/admin/tags')
		})

		// Issue #194: generation order is install order, so an insertion-ordered
		// manifest hands two developers who added the same bundles in a different
		// sequence two different files. Canonical order makes `routes.ts` a
		// function of what is installed, not of when each part arrived.
		it('keeps the array sorted by path, whatever the insertion order', () => {
			const insert = (source: string, path: string) =>
				addRouteToManifest(source, { path, file: `.${path}.tsx` })
			const forward = ['/a', '/m', '/z'].reduce(insert, EMPTY_ROUTES_MANIFEST)
			const backward = ['/z', '/m', '/a'].reduce(insert, EMPTY_ROUTES_MANIFEST)
			expect(backward).toBe(forward)
			expect(forward.indexOf("'/a'")).toBeLessThan(forward.indexOf("'/m'"))
			expect(forward.indexOf("'/m'")).toBeLessThan(forward.indexOf("'/z'"))
		})

		it('does not corrupt surrounding code the way string splice would', () => {
			// A routes file whose comment mentions the old anchor string.
			const src = [
				"// historically this was spliced via .replace('pages: []', …)",
				'export const routes = []',
			].join('\n')
			const out = addRouteToManifest(src, {
				path: '/x',
				file: './routes/x.tsx',
			})
			// The comment (which contains a fake anchor) is untouched.
			expect(out).toContain('// historically this was spliced')
			expect(out).toContain("path: '/x'")
		})
	})
})

describe('never-clobber writer + eject', () => {
	/**
	 * Issue #349: the banner has to say which half is yours.
	 *
	 * Eject is advertised as whole-page ownership. What it hands over owns the
	 * render; the loader behind it is still framework code that resolves this
	 * page from `spec/` on every request. Three lines that said only "you own
	 * this file now" read as "this file is the whole page", and users found out
	 * otherwise by deleting the spec entry and watching the route disappear.
	 */
	it('names the half of the page the ejected file does NOT own', () => {
		expect(EJECT_BANNER).toContain('EJECTED')
		expect(EJECT_BANNER).toMatch(/LOADER/)
		expect(EJECT_BANNER).toMatch(/spec\//)
		// Every line is a comment — this is prepended to a source file.
		for (const line of EJECT_BANNER.split('\n')) {
			expect(line.startsWith('//')).toBe(true)
		}
	})

	it('creates then leaves an unchanged generated file alone', async () => {
		const fs = createMemFs()
		let m = emptyManifest()
		const entry = {
			id: 'task',
			routePath: '/admin/tasks',
			file: 'routes/task.tsx',
		}
		const first = await writeGenerated(fs, m, entry, 'v1')
		m = first.manifest
		expect(first.result.action).toBe('created')

		const second = await writeGenerated(fs, m, entry, 'v1')
		expect(second.result.action).toBe('unchanged')

		const third = await writeGenerated(fs, second.manifest, entry, 'v2')
		expect(third.result.action).toBe('overwritten')
		expect(await fs.read('routes/task.tsx')).toBe('v2')
	})

	it('never overwrites an ejected file', async () => {
		const fs = createMemFs()
		let m = emptyManifest()
		const entry = {
			id: 'task',
			routePath: '/admin/tasks',
			file: 'routes/task.tsx',
		}
		m = (await writeGenerated(fs, m, entry, '// AUTO-GENERATED\n\nbody'))
			.manifest

		const ejected = await eject(fs, m, 'task', 'custom-pages/task.tsx')
		m = ejected.manifest
		expect(ejected.result.action).toBe('created')
		const ejectedContent = await fs.read('custom-pages/task.tsx')
		expect(ejectedContent).toContain('EJECTED')
		expect(ejectedContent).toContain('body')
		expect(ejectedContent).not.toContain('AUTO-GENERATED')

		// A regeneration attempt on the ejected id is refused.
		const retry = await writeGenerated(fs, m, entry, 'NEW')
		expect(retry.result.action).toBe('skipped-user-owned')
	})

	it('swaps the banner when ejecting in place — the default path', async () => {
		// `maxstack eject <id>` with no `--to` ejects to the file that is already
		// there. That destination always exists, and treating it as the
		// already-owned case left the file claiming `DO NOT EDIT — regeneration
		// overwrites this file` immediately after the manifest made that false.
		const fs = createMemFs()
		let m = emptyManifest()
		const entry = {
			id: 'task',
			routePath: '/admin/tasks',
			file: 'routes/task.tsx',
		}
		m = (await writeGenerated(fs, m, entry, '// AUTO-GENERATED\n\nbody'))
			.manifest

		const ejected = await eject(fs, m, 'task', entry.file)
		m = ejected.manifest
		expect(ejected.result.action).toBe('overwritten')
		expect(ejected.result.ownership).toBe('ejected')
		const content = await fs.read(entry.file)
		expect(content).toContain('EJECTED — you own this file now')
		expect(content).not.toContain('AUTO-GENERATED')
		expect(content).toContain('body')

		// Still frozen against regeneration, and a second eject is a no-op that
		// does not stack a second banner.
		expect((await writeGenerated(fs, m, entry, 'NEW')).result.action).toBe(
			'skipped-user-owned',
		)
		const again = await eject(fs, m, 'task', entry.file)
		expect(again.result.action).toBe('skipped-user-owned')
		expect(await fs.read(entry.file)).toBe(content)
	})

	it('still refuses to clobber a different destination that already exists', async () => {
		const fs = createMemFs()
		let m = emptyManifest()
		const entry = {
			id: 'task',
			routePath: '/admin/tasks',
			file: 'routes/task.tsx',
		}
		m = (await writeGenerated(fs, m, entry, '// AUTO-GENERATED\n\nbody'))
			.manifest
		await fs.write('custom-pages/task.tsx', 'mine, written by hand')

		const ejected = await eject(fs, m, 'task', 'custom-pages/task.tsx')
		expect(ejected.result.action).toBe('skipped-user-owned')
		expect(await fs.read('custom-pages/task.tsx')).toBe('mine, written by hand')
	})

	/**
	 * `writeOwned` — the writer behind `maxstack add view` (issue #360), which
	 * until then wrote its user-owned module with a bare `fs.write`.
	 *
	 * The interesting property is that it is neither of the other two: it must
	 * write over a `generated` module (that is the infer-then-eject workflow) and
	 * refuse everything else, which is `writeGenerated`'s ownership rule landing
	 * an `ejected` entry.
	 */
	describe('writeOwned', () => {
		const entry = {
			id: 'task',
			routePath: '/admin/tasks',
			file: 'routes/task.tsx',
		}

		it('writes over a generated module and lands it ejected', async () => {
			const fs = createMemFs()
			const gen = await writeGenerated(fs, emptyManifest(), entry, '// GEN')
			const owned = await writeOwned(fs, gen.manifest, entry, 'MINE')
			expect(owned.result.action).toBe('overwritten')
			expect(owned.result.ownership).toBe('ejected')
			expect(await fs.read(entry.file)).toBe('MINE')
		})

		it('refuses the second run — the clobber that shipped', async () => {
			const fs = createMemFs()
			const first = await writeOwned(fs, emptyManifest(), entry, 'MINE')
			expect(first.result.action).toBe('created')
			await fs.write(entry.file, 'MINE, then hand-edited')

			const second = await writeOwned(fs, first.manifest, entry, 'SCAFFOLD v2')
			expect(second.result.action).toBe('skipped-user-owned')
			expect(second.result.ownership).toBe('ejected')
			expect(await fs.read(entry.file)).toBe('MINE, then hand-edited')
			// The manifest is returned unchanged, so a caller that persists the
			// result cannot re-stamp an entry over a write that did not happen.
			expect(second.manifest).toBe(first.manifest)
		})

		it('refuses a file on disk the manifest has never heard of', async () => {
			// No entry to consult, so a manifest-only ownership test would clobber
			// it. Somebody wrote those bytes; nobody generated them.
			const fs = createMemFs({ 'routes/task.tsx': 'hand-written' })
			const res = await writeOwned(fs, emptyManifest(), entry, 'SCAFFOLD')
			expect(res.result.action).toBe('skipped-user-owned')
			expect(await fs.read(entry.file)).toBe('hand-written')
		})

		it('refuses when a DIFFERENT id already owns the same path', async () => {
			// An `eject --to` this file, or a slot file. Same data loss, different
			// name — which is why the check is on the file as well as the id.
			const fs = createMemFs({ 'routes/task.tsx': 'ejected elsewhere' })
			const m = upsertEntry(emptyManifest(), {
				id: 'legacy-task',
				routePath: '/admin/tasks',
				file: 'routes/task.tsx',
				ownership: 'ejected',
			})
			const res = await writeOwned(fs, m, entry, 'SCAFFOLD')
			expect(res.result.action).toBe('skipped-user-owned')
			expect(await fs.read(entry.file)).toBe('ejected elsewhere')
		})

		it('overwrites owned code only under force', async () => {
			const fs = createMemFs({ 'routes/task.tsx': 'hand-written' })
			const res = await writeOwned(fs, emptyManifest(), entry, 'SCAFFOLD', {
				force: true,
			})
			expect(res.result.action).toBe('overwritten')
			expect(await fs.read(entry.file)).toBe('SCAFFOLD')
		})
	})
})

describe('generateResourcePage (orchestration on the small target)', () => {
	it('produces a framework route, a user slot file, a routes entry, and a manifest', async () => {
		const fs = createMemFs()
		const { manifest } = await generateResourcePage(fs, TASK)
		const paths = pageFilePaths('task')

		const files = fs.snapshot()
		expect(files.has(paths.routeFile)).toBe(true)
		expect(files.has(paths.slotFile)).toBe(true)
		expect(files.has(paths.routesManifest)).toBe(true)
		expect(files.has(MANIFEST_FILENAME)).toBe(true)

		expect(files.get(paths.routesManifest)).toContain('/admin/tasks')

		const route = manifest.entries.find((e) => e.id === 'task')
		expect(route?.ownership).toBe('generated')
		expect(manifest.entries.find((e) => e.id === 'task:slot')?.ownership).toBe(
			'user',
		)

		// Round-trips through the on-disk manifest.
		expect(parseManifest(files.get(MANIFEST_FILENAME) ?? '')).toEqual(manifest)
	})

	it('regenerating does not clobber a user-edited slot file', async () => {
		const fs = createMemFs()
		await generateResourcePage(fs, TASK)
		const paths = pageFilePaths('task')

		// User edits their slot file.
		const edited =
			'export function afterList() {\n\treturn <button>Bulk archive</button>\n}\n'
		await fs.write(paths.slotFile, edited)

		// Regenerate (e.g. title changed) — the route file may change, the slot must not.
		await generateResourcePage(fs, { ...TASK, title: 'All Tasks' })

		expect(await fs.read(paths.slotFile)).toBe(edited)
		expect(await fs.read(paths.routeFile)).toContain('All Tasks')
	})

	it('scaffolds a stub for a slot added to a live page (no dangling ref), preserving user edits', async () => {
		const fs = createMemFs()
		await generateResourcePage(fs, TASK)
		const paths = pageFilePaths('task')

		// The user fills the seeded slot with real code.
		const edited =
			'export function afterList() {\n\treturn <button>Bulk archive</button>\n}\n'
		await fs.write(paths.slotFile, edited)

		// A new slot is added to the already-live page (the `page.addBlock` case).
		await generateResourcePage(fs, {
			...TASK,
			slots: ['afterList', 'filters'],
		})

		const slotFile = await fs.read(paths.slotFile)
		// The user's existing code survives byte-for-byte...
		expect(slotFile.startsWith(edited)).toBe(true)
		// ...and the new slot's render stub was appended, so `slots.filters` resolves.
		expect(slotFile).toContain('export function filters()')
		expect(await fs.read(paths.routeFile)).toContain('render={slots.filters}')

		// Idempotent: regenerating with the same slots appends nothing.
		const before = await fs.read(paths.slotFile)
		await generateResourcePage(fs, { ...TASK, slots: ['afterList', 'filters'] })
		expect(await fs.read(paths.slotFile)).toBe(before)
	})
})

describe('regeneration-as-diff (bet B)', () => {
	function targetFor(content: string): RegenTarget {
		return {
			id: 'task',
			file: 'routes/task.tsx',
			routePath: '/admin/tasks',
			nextContent: content,
		}
	}

	it('reports a reviewable diff instead of writing', async () => {
		const fs = createMemFs({ 'routes/task.tsx': 'old\n' })
		const review = await regenerateAsDiff(fs, emptyManifest(), [
			targetFor('new\n'),
		])
		expect(review.hasChanges).toBe(true)
		const file = review.files[0]
		expect(file?.status).toBe('modified')
		expect(file?.patch).toContain('-old')
		expect(file?.patch).toContain('+new')
		// Nothing was written.
		expect(await fs.read('routes/task.tsx')).toBe('old\n')
	})

	it('marks protected (ejected/user) files and never proposes overwriting them', async () => {
		const fs = createMemFs({ 'routes/task.tsx': 'user code\n' })
		const m = upsertEntry(emptyManifest(), {
			id: 'task',
			routePath: '/admin/tasks',
			file: 'routes/task.tsx',
			ownership: 'ejected',
		})
		const review = await regenerateAsDiff(fs, m, [targetFor('regenerated\n')])
		expect(review.files[0]?.status).toBe('protected')
		expect(review.files[0]?.protectedReason).toBe('ejected')
		expect(review.hasChanges).toBe(false)
	})

	it('lands a diff only when the validate gate passes', async () => {
		const fs = createMemFs({ 'routes/task.tsx': 'old\n' })
		const targets = [targetFor('new\n')]
		const review = await regenerateAsDiff(fs, emptyManifest(), targets)

		const rejected = await applyReviewedDiff(
			fs,
			emptyManifest(),
			targets,
			review,
			async () => ({
				ok: false,
				reason: 'typecheck failed',
			}),
		)
		expect(rejected.rejected).toBe('typecheck failed')
		expect(await fs.read('routes/task.tsx')).toBe('old\n')

		const landed = await applyReviewedDiff(
			fs,
			emptyManifest(),
			targets,
			review,
			async () => ({
				ok: true,
			}),
		)
		expect(landed.written).toEqual(['routes/task.tsx'])
		expect(await fs.read('routes/task.tsx')).toBe('new\n')
		expect(landed.manifest.entries.find((e) => e.id === 'task')?.hash).toBe(
			hashContent('new\n'),
		)
	})
})

describe('regeneration-safety suite', () => {
	it('passes when only generated files changed', () => {
		const before: FsSnapshot = {
			manifest: upsertEntry(emptyManifest(), {
				id: 'task',
				routePath: '/admin/tasks',
				file: 'routes/task.tsx',
				ownership: 'generated',
			}),
			files: new Map([['routes/task.tsx', 'v1']]),
		}
		const after: FsSnapshot = {
			manifest: before.manifest,
			files: new Map([['routes/task.tsx', 'v2']]),
		}
		expect(checkRegenSafety(before, after)).toEqual([])
	})

	it('flags a modified ejected/user file (never-clobber violation)', () => {
		const manifest = upsertEntry(emptyManifest(), {
			id: 'task',
			routePath: '/admin/tasks',
			file: 'custom-pages/task.tsx',
			ownership: 'ejected',
		})
		const before: FsSnapshot = {
			manifest,
			files: new Map([['custom-pages/task.tsx', 'mine']]),
		}
		const after: FsSnapshot = {
			manifest,
			files: new Map([['custom-pages/task.tsx', 'clobbered']]),
		}
		const violations = checkRegenSafety(before, after)
		expect(violations).toHaveLength(1)
		expect(violations[0]?.invariant).toBe('never-clobber')
	})

	it('flags an ownership regression away from ejected', () => {
		const before: FsSnapshot = {
			manifest: upsertEntry(emptyManifest(), {
				id: 'task',
				routePath: '/admin/tasks',
				file: 'custom-pages/task.tsx',
				ownership: 'ejected',
			}),
			files: new Map([['custom-pages/task.tsx', 'mine']]),
		}
		const after: FsSnapshot = {
			manifest: upsertEntry(emptyManifest(), {
				id: 'task',
				routePath: '/admin/tasks',
				file: 'custom-pages/task.tsx',
				ownership: 'generated',
			}),
			files: new Map([['custom-pages/task.tsx', 'mine']]),
		}
		expect(checkRegenSafety(before, after).map((v) => v.invariant)).toContain(
			'ownership-preserved',
		)
	})

	describe('data-level provenance invariants', () => {
		type Row = { key: string; isAddedManually?: boolean; isAccepted?: boolean }
		const key = (r: Row) => r.key

		it('passes when manual rows survive and grounding is all-accepted', () => {
			const before: Row[] = [{ key: 'a', isAddedManually: true }, { key: 'b' }]
			const after: Row[] = [{ key: 'a', isAddedManually: true }]
			const grounding: Row[] = [{ key: 'c', isAccepted: true }]
			expect(checkProvenanceInvariants(before, after, grounding, key)).toEqual(
				[],
			)
		})

		it('flags a deleted manual row', () => {
			const before: Row[] = [{ key: 'a', isAddedManually: true }]
			const violations = checkProvenanceInvariants(before, [], [], key)
			expect(violations[0]?.invariant).toBe('manual-survives')
		})

		it('flags grounding on an unaccepted row', () => {
			const grounding: Row[] = [{ key: 'c', isAccepted: false }]
			const violations = checkProvenanceInvariants([], [], grounding, key)
			expect(violations[0]?.invariant).toBe('grounds-on-accepted')
		})
	})
})

describe('the generation watermark', () => {
	// The one fact on disk that says whether anything was ever *derived* from a
	// decision. The spec cannot answer it about itself, so it lives on the
	// manifest, and the review surfaces' undo offer hangs off it.

	it('is absent until something records one', () => {
		expect(generationWatermark(emptyManifest())).toBeNull()
	})

	it('never moves backwards', () => {
		// A run that somehow saw a shorter log than the last one must not un-say
		// "this was generated from". The watermark answers a question whose answer
		// only ever goes from no to yes.
		const stamped = recordGeneration(emptyManifest(), 12)
		expect(generationWatermark(recordGeneration(stamped, 4))).toBe(12)
		expect(generationWatermark(recordGeneration(stamped, 13))).toBe(13)
	})

	it('leaves the manifest it was given alone', () => {
		const before = emptyManifest()
		recordGeneration(before, 7)
		expect(before.generatedFromOpCount).toBeUndefined()
	})

	it('survives a round trip, and a manifest written before it existed still parses', () => {
		const raw = serializeManifest(recordGeneration(emptyManifest(), 5))
		expect(generationWatermark(parseManifest(raw))).toBe(5)
		// The pre-#245 shape: no field at all. Reads as "nothing generated" rather
		// than failing, so an existing project is not bricked by the upgrade.
		expect(
			generationWatermark(parseManifest('{"version":1,"entries":[]}')),
		).toBeNull()
	})
})
