import { describe, expect, it } from 'vitest'
import { createMemFs } from './memfs.ts'
import {
	emitScheduleHandlerStub,
	emitScheduleRegistry,
	generateSchedules,
	type ScheduleDescriptor,
	scheduleFilePaths,
	scheduleModuleName,
} from './schedules.ts'

const descriptor = (
	key: string,
	overrides: Partial<ScheduleDescriptor> = {},
): ScheduleDescriptor => ({
	key,
	description: `the ${key} job`,
	runAs: 'service role "scheduler"',
	recurrence: 'daily at 09:00 UTC',
	...overrides,
})

describe('schedule file paths', () => {
	it('turns a dotted key into a filesystem-safe module name', () => {
		expect(scheduleModuleName('invoice.recurring')).toBe('invoice-recurring')
		expect(scheduleFilePaths('invoice.recurring').handlerFile).toBe(
			'jobs/invoice-recurring.handler.ts',
		)
	})
})

describe('generateSchedules', () => {
	it('emits nothing at all when no schedule is declared', async () => {
		const fs = createMemFs()
		await generateSchedules(fs, [])
		expect([...fs.snapshot().keys()]).toEqual([])
	})

	it('emits a framework registry and a user-owned handler stub per schedule', async () => {
		const fs = createMemFs()
		const { results } = await generateSchedules(fs, [
			descriptor('invoice.recurring'),
		])
		const files = fs.snapshot()
		expect(files.has('jobs/schedules.generated.ts')).toBe(true)
		expect(files.has('jobs/invoice-recurring.handler.ts')).toBe(true)
		expect(results.map((r) => r.ownership)).toContain('user')
		expect(results.map((r) => r.ownership)).toContain('generated')
	})

	it('NEVER rewrites a filled handler, but does refresh the registry', async () => {
		// The whole value of the seam: user code inside it is as safe as an
		// ejected file, without the maintainer paying the eject tax.
		const fs = createMemFs()
		await generateSchedules(fs, [descriptor('invoice.recurring')])
		const mine = '// SM-2 lives here\nexport default async function () {}\n'
		await fs.write('jobs/invoice-recurring.handler.ts', mine)

		await generateSchedules(fs, [
			descriptor('invoice.recurring'),
			descriptor('digest.daily'),
		])
		expect(await fs.read('jobs/invoice-recurring.handler.ts')).toBe(mine)
		const registry = await fs.read('jobs/schedules.generated.ts')
		expect(registry).toContain("'digest.daily'")
		expect(registry).toContain("'invoice.recurring'")
	})

	it('is deterministic — declaration order does not change the output', async () => {
		const a = createMemFs()
		const b = createMemFs()
		await generateSchedules(a, [descriptor('b.two'), descriptor('a.one')])
		await generateSchedules(b, [descriptor('a.one'), descriptor('b.two')])
		expect(await a.read('jobs/schedules.generated.ts')).toBe(
			await b.read('jobs/schedules.generated.ts'),
		)
	})

	it('is idempotent — a second run with the same input changes nothing', async () => {
		const fs = createMemFs()
		await generateSchedules(fs, [descriptor('a.one')])
		const { results } = await generateSchedules(fs, [descriptor('a.one')])
		expect(results.map((r) => r.action)).toEqual([
			'unchanged',
			'skipped-user-owned',
		])
	})
})

describe('the emitted stub', () => {
	it('states the at-least-once contract where the author will read it', async () => {
		// Not in a doc nobody opens: a handler that ignores the idempotency key
		// will eventually double-charge somebody, so the warning ships with the
		// file the author is about to edit.
		const stub = emitScheduleHandlerStub(descriptor('invoice.recurring'))
		expect(stub).toMatch(/at-least-once/i)
		expect(stub).toMatch(/idempotencyKey/)
		expect(stub).toMatch(/service role "scheduler"/)
		expect(stub).toMatch(/daily at 09:00 UTC/)
	})

	it('marks the registry as generated so nobody edits it by mistake', () => {
		expect(emitScheduleRegistry([descriptor('a.one')])).toMatch(
			/GENERATED by maxstack/,
		)
	})
})
