/**
 * **The scheduling extension point** — the generated half.
 *
 * A declared schedule (`schedules.declare`) says *when* work runs, who it runs
 * as, and in which timezone. It deliberately does not say *what* the work is:
 * absorbing "compute the next SM-2 due date from the review grade" into a spec
 * op would be the framework-as-cage failure — the vocabulary would grow a
 * spaced-repetition operator, and the next product would want a different one.
 *
 * So the platform generates the seam and the user fills it:
 *
 *   - `jobs/schedules.generated.ts` — **framework-owned**. A registry mapping
 *     every declared schedule key to its handler, re-emitted on every
 *     regeneration. Declaring a schedule wires it; nobody edits this file.
 *   - `jobs/<key>.handler.ts` — **user-owned, written once**. The typed slot the
 *     scheduler calls. Regeneration never touches it again, so the domain logic
 *     inside is as safe as any ejected file without paying the eject tax.
 *
 * That is what moves an ask like cardstack's SM-2 scheduler from *off-surface*
 * (weight 8: no op, no slot, no guidance) to *slot fill* (weight 3: the platform
 * said where the code goes, called it with a typed context, and promised not to
 * overwrite it). The honesty of the win is in what did **not** happen — the op
 * vocabulary did not learn about spaced repetition.
 */

import {
	MANIFEST_FILENAME,
	parseManifest,
	type RouteManifest,
	serializeManifest,
} from './manifest.ts'
import type { Fs, WriteResult } from './write.ts'
import { writeGenerated, writeUserFileOnce } from './write.ts'

/** What the generator needs to know about one declared schedule. */
export interface ScheduleDescriptor {
	/** The declared key, e.g. `invoice.recurring`. */
	key: string
	/** One line, rendered into the stub so the file explains itself. */
	description: string
	/** Rendered into the stub's header — the reviewer's cue about authority. */
	runAs: string
	/** Rendered into the stub's header — prose, not a cron string. */
	recurrence: string
}

/** A schedule key as a filesystem-safe module name (`a.b` → `a-b`). */
export function scheduleModuleName(key: string): string {
	return key.replace(/[^a-z0-9]+/gi, '-').replace(/^-|-$/g, '')
}

/** Where a schedule's files live, relative to the project root. */
export function scheduleFilePaths(key: string): {
	handlerFile: string
	registryFile: string
} {
	return {
		handlerFile: `jobs/${scheduleModuleName(key)}.handler.ts`,
		registryFile: 'jobs/schedules.generated.ts',
	}
}

/**
 * The user-owned handler stub. Written once and never again, so everything in
 * it is a decision the maintainer gets to keep.
 *
 * The stub says the delivery semantics out loud rather than in a doc nobody
 * opens. At-least-once is not a caveat here, it is the contract: the same
 * `ctx.idempotencyKey` can arrive twice (a worker that died between doing the
 * work and recording it has no way to know which side of that line it was on),
 * and a handler that ignores it will eventually double-charge somebody.
 */
export function emitScheduleHandlerStub(
	descriptor: ScheduleDescriptor,
): string {
	return [
		`/**`,
		` * Handler slot for the "${descriptor.key}" schedule — YOURS.`,
		` *`,
		` * ${descriptor.description}`,
		` *`,
		` * Runs ${descriptor.recurrence}, as ${descriptor.runAs}.`,
		` *`,
		` * This file is written once and never regenerated: edit it freely.`,
		` *`,
		` * **Delivery is at-least-once.** \`ctx.idempotencyKey\` is stable per`,
		` * occurrence — the same key can arrive twice if a worker dies between`,
		` * doing the work and recording that it did. Key your writes on it (or on`,
		` * something derived from it) and a repeat becomes a no-op. Nothing else`,
		` * in the system can make this exactly-once, and claiming otherwise would`,
		` * be a lie that costs money the first time it matters.`,
		` */`,
		``,
		`import type { ScheduleHandlerContext } from '@maxstack/features/jobs'`,
		``,
		`export default async function handler(`,
		`\tctx: ScheduleHandlerContext,`,
		`): Promise<void> {`,
		`\t// TODO: the work. \`ctx.runAs\` is the identity to do it under —`,
		`\t// resolve permissions from it rather than assuming admin.`,
		`\tvoid ctx`,
		`}`,
		``,
	].join('\n')
}

/** The framework-owned registry: declared key → handler module. */
export function emitScheduleRegistry(
	descriptors: readonly ScheduleDescriptor[],
): string {
	const sorted = [...descriptors].sort((a, b) => a.key.localeCompare(b.key))
	const imports = sorted.map(
		(d, i) =>
			`import handler${i} from './${scheduleModuleName(d.key)}.handler.ts'`,
	)
	const entries = sorted.map((d, i) => `\t'${d.key}': handler${i},`)
	return [
		'// GENERATED by maxstack — do not edit.',
		'//',
		'// The declared schedules and the handler slot each one calls. Regenerated',
		'// from `schedules.json` on every build; the handler modules it imports are',
		'// yours and are never rewritten.',
		'',
		"import type { ScheduleHandler } from '@maxstack/features/jobs'",
		...imports,
		'',
		'export const scheduleHandlers: Record<string, ScheduleHandler> = {',
		...entries,
		'}',
		'',
	].join('\n')
}

export interface ScheduleGenerateResult {
	manifest: RouteManifest
	results: WriteResult[]
}

async function loadManifest(fs: Fs): Promise<RouteManifest> {
	if (await fs.exists(MANIFEST_FILENAME)) {
		return parseManifest(await fs.read(MANIFEST_FILENAME))
	}
	return { version: 1, entries: [] }
}

/**
 * Generate the scheduling seam for every declared schedule. Idempotent: the
 * registry is rewritten only when its content changed, and each handler stub is
 * written once and never again.
 *
 * A project with no declared schedules emits **nothing** — not an empty
 * registry. The same absence rule the spec layer uses: a project that never
 * declared recurrence should not grow a `jobs/` directory to prove it.
 */
export async function generateSchedules(
	fs: Fs,
	descriptors: readonly ScheduleDescriptor[],
): Promise<ScheduleGenerateResult> {
	let manifest = await loadManifest(fs)
	const results: WriteResult[] = []
	if (descriptors.length === 0) return { manifest, results }

	const registryFile = scheduleFilePaths('_').registryFile
	const registry = await writeGenerated(
		fs,
		manifest,
		{ id: 'schedules:registry', routePath: '', file: registryFile },
		emitScheduleRegistry(descriptors),
	)
	manifest = registry.manifest
	results.push(registry.result)

	for (const descriptor of descriptors) {
		const { handlerFile } = scheduleFilePaths(descriptor.key)
		const written = await writeUserFileOnce(
			fs,
			manifest,
			`schedule:${descriptor.key}`,
			handlerFile,
			emitScheduleHandlerStub(descriptor),
		)
		manifest = written.manifest
		results.push(written.result)
	}

	await fs.write(MANIFEST_FILENAME, serializeManifest(manifest))
	return { manifest, results }
}
